.PHONY: all
all: hw4pr3 hw4pr4

hw4pr4: hw4pr4.c
	gcc --std="gnu17" -o hw4pr4 hw4pr4.c

hw4pr4-debug: hw4pr4.c
	gcc --std="gnu17" -ggdb -o hw4pr4 hw4pr4.c

hw4pr3: hw4pr3.c
	gcc -o hw4pr3 -std="gnu11" hw4pr3.c
