#!/usr/bin/env bash

if [ "$#" -lt "1" ]; then
    echo "Usage: $0 [pset-num]"
    echo
    echo "Usage example: $0 5"
    exit 1
fi

curl --output "pset-w0$1.pdf" -L "http://faculty.cooper.edu/hak/ece357/pset-w0$1.pdf"

